### ISSUE TITLE
Mailing list ownership

### ISSUE THREAD

**Issue by pcuci** [bettermtl/bettermtl.github.io#26]
Who's got the right to email the full/subset list of members who sign up?

Related to #17

**Comment by David-Ro** [comment]
hierarchy similar to executive committee modeled in speedteam Trello where
the group needed a head, secretary, 2ic (and can have also up to 5 others
whose title is VP of __ or director of __); each titledholder is ranked 1st
2nd 3rd 4th etc for their ability to act unilaterally and to override the
others steps taken. This committee is an advance-report-sharing group, not
a voting parliament. If stalemate or "polemic" then this committee reports
to the operational team, i.e. all those who are active per recency of
presence, and these are the people who vote, to ratify approve annul
reverse etc.

**Comment by David-Ro** [comment]
Elect to avoid this concern totally.

**Comment by pcuci** [comment]
A future world needs no email. Decentralized applications have their own id'ing and communications systems.

Imagine sending to an aptitude team, not to any one individual.

All core/top contributors have access to the mailing list. We can arbitrarily choose top 5 contributors in the past 2 months. This doesn't mean they can copy the full list and use to their purposes, only that they can email the list while they maintain top contributor status.

Closing for now, explore governance further in #18
