### ISSUE TITLE
Purchase and setup domain name

### ISSUE THREAD

**Issue by pcuci** [bettermtl/bettermtl.github.io#27]
Paid for http://bettermtl.com
- [x] purchase domain name
- [x] setup google apps domain
- [x] setup emails

**Comment by David-Ro** [comment]
Can this "issue" ticket include autoresponder emails and automatically generating new email addresses?

**Comment by pcuci** [comment]
No. See #43

**Comment by pcuci** [comment]
@David-Ro you have david (at) bettermtl.com setup, I can receive mail paul (at) bettermtl.com too
