### ISSUE TITLE
Identify early adopters

### ISSUE THREAD

**Issue by pcuci** [bettermtl/bettermtl.github.io#29]
High tech organizers to begin with

**Comment by pcuci** [comment]
@frabrunelle which other organizers should co-build this platform with us?

**Comment by David-Ro** [comment]
To locate early adopters: see those who 
THESE:
hold events
dissatisfied with (meetup eventbrite FB etc)
willing to begin posting here

What to do to bring them in: Show, model, behavior that they copy. Support, help, correct their mistakes, behind the scenes (doing something that's non scalable, to build growth for a time).

**Comment by pcuci** [comment]
Related to #2 (curate upcoming events)

**Comment by pcuci** [comment]
@jeffyactive wants hashtags for locations: #74. Need explore IoT integrations too

@MattyChance would it be possible to elect http://bettermtl.com as a shared team project for FreeCodeCamp Montreal?

FreeCodeCamp participants can learn/warm up their GitHub collaborative development skills and start contributing meaningfully to a real community project. Later, contributors can send pull-requests too. We don't mind if people break things - only way to learn!

@JonathanChaloux wants the monthly calendar for Le Salon 1861 to be generated automatically on http://bettermtl.com - today he uses canva.com to put together a nice graphic for the monthly calendar (non-interactive) - will loop in @firearbete75 re: socent overlap

Similarly, @olioli and StartupDigest could use the curation/co-editing/Wikipedia-like features to together build up the weekly newsletter, with the community.

@mattmanis @carocvin are exploring the overlap between chapOrange, VertMTL and http://bettermtl.com: https://trello.com/b/HQDFrFYf/vertmtl - a different view (green-tech) to the same data might work as a different brand http://vertmtl.org (once http://ocpm.qc.ca/vertmtl/marathon hands it over to the community)

@tokenrove wants to shift http://www.meetup.com/Papers-We-Love-Montreal/ to using http://bettermtl.com

**Comment by pcuci** [comment]
@David-Ro other than @olioli and the slightly better coordinated montrealintechnology calendar/social-media-postings I don't see any innovators in the event-management space in Montreal.

Maybe http://www.initlive.com/ (Ottawa) and http://pixmob.com/ - but they target professional event organizers, not grass-roots community organizers

Most community organizers are happy with Eventbrite/Facebook and keep complaining about meetup.com. Also weezevent.com (French-first, made by the Swiss) and https://www.universe.com/ (FounderFuel grads) have gained a little adoption

**Comment by pcuci** [comment]
@David-Ro - I created labels for roles @ and customers #: https://github.com/bettermtl/bettermtl.github.io/labels - we can use to further help prioritize items, i.e.: who would appreciate a feature most

**Comment by David-Ro** [comment]
PWL. Papers-We-Love-Montreal. Also, Julian Squires @tokenrove is the Montreal host of the functional programming joint-grouped meetup and he's said to include this group also.
