### ISSUE TITLE
Schedule recurring tech team ghangout

### ISSUE THREAD

**Issue by pcuci** [bettermtl/bettermtl.github.io#35]
Doodle a good time for all interested

Need to touch base with all community stakeholders, regularly.

Open invite

**Comment by David-Ro** [comment]
We can start "touch base" hangouts after we get (a series of two) objectives and key results. The hangouts can become regular events and can retire issue 40.

**Comment by pcuci** [comment]
We'll sync up with contributors primarily in real life @carocvin @JonathanChaloux @MiotaScott @heri - no need to sync up weekly, just shoot a comment in gitter https://gitter.im/bettermtl/general
