### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by David-Ro** [bettermtl/bettermtl.github.io#36]

**Comment by David-Ro** [comment]
absolves you and your heirs from damages caused as the result of using BetterMTL and/or related information given or received under any circumstances.
1. Use of BetterMTL constitutes acceptance of the terms of this agreement.
2. BetterMTL will not be held responsible…
3. Cancellation of an event
        3a. If with…
        3b. If without …
etc.,
Disagree        Agree

**Comment by pcuci** [comment]
Need a simple EULA, e.g.: you and us own the data and metadata.

Trust the information on this site at your expense.

There are fair EULAs short and sweet, put together by the F/LOSS groups,
can use one of those.

**Comment by pcuci** [comment]
Added the [MIT License](https://github.com/bettermtl/bettermtl.github.io/blob/master/LICENSE) for free/open source code and data - anyone can use everything for whatever purpose

**Comment by pcuci** [comment]
@David-Ro see this licence for data: http://opendatacommons.org/licenses/odbl/summary/
