### ISSUE TITLE
OKR: objectives, key results

### ISSUE THREAD

**Issue by David-Ro** [bettermtl/bettermtl.github.io#40]
objectifs et résultats-clés, par intervalles de 3 à 6 semaines.

**Comment by David-Ro** [comment]
dresser une liste (aider à dresser la liste) d'objectifs et résultats-clés.

**Comment by David-Ro** [comment]
relates to issue #35, regular hangouts of the core tech doers

**Comment by pcuci** [comment]
plan a couple weeks ahead (ready list) and dump everything else in backlog, for later, once we achieve some micro-deliverables

**Comment by David-Ro** [comment]
1. prove we can link the events to a calendar, a blog, an emailed newsletter. Then collaboratively do so.
   2.
