### ISSUE TITLE
Locations/rooms data

### ISSUE THREAD

**Issue by pcuci** [bettermtl/bettermtl.github.io#56]
Data remodel to re-use locations

Investigate using http://jekyll.tips/guide/collections/

**Comment by David-Ro** [comment]
This shall always need curation, in every city. Use postal code as a cornerstone, keystone-arch, key element, if it's provided or when a curator adds it. Fallback to lattitude longitude also. Meetup does this. (FYI, Why it needs curation:  many possible different descriptions for each door of each room of each building. endFYI) Allow for each location to be described in multiple ways (pick options) and for the wiki-organizers to choose a primary description for that event (event stream) as the "chosen" version for language X and language Y.  Allow all viewers to see all the other acceptable descriptions of the location (some buildings and enterprises have had multiple names and they allow anyone to use one of the former names as an identifier, so previous names are not forgotten. Also, maps programs all might have different building names: BB, Apple, Yahoo, Bing, Waze, Google etc). Same confusion multiplicity applies to streets, their names, and to street "corners" known as "Place de la... " Allow photo attachment to show what the place looks like when arriving by street (bike, bus, car), by footpath. Allow note to show locations for bike parking vicinity, etc.

**Comment by David-Ro** [comment]
Show the vague data, first and foremost: e.g. "it's at Notman" That is part 1 of 3 things that people want to know.  People want to know 2 more things: that The Administrators have given this event A Room, and that the software will give them the details (which room, which staircase) when they arrive or a few minutes earlier.
So, when pre-event chatter is occurring, this is when to display the exquisitely detailed room information. So the information is layered, time sequenced: reveal partial disclosure, gradual disclosure. With Proof of Approval of A Room.

**Comment by pcuci** [comment]
@David-Ro locations data model now allows for these extensions to be made possible. Closing the issue now, please extract any specific features you wanted from here into the relevant milestone wikiBoto/wikiCrono/etc. if any are high priority
